# -*- coding: utf-8 -*-
"""1_Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjouZ0V8PHd1Rgscu4xckf_1I3QPKjFH

Here, a Linear Regression model is implemented. Different scenarios are tested with the data and the model. I warmly encourage you to play with the data frame and test variations of the parameters. The result could be improved if the outliers are removed. This is another optimisation that you could test.

## 0. Import Data and Overview it
"""

medical_charges_url = 'https://raw.githubusercontent.com/JovianML/opendatasets/master/data/medical-charges.csv'

from urllib.request import urlretrieve

urlretrieve(medical_charges_url, "data/medical.csv")        # Create data folder or just store the file medical.csv

import pandas as pd

medical_df = pd.read_csv("data/medical.csv").convert_dtypes()

medical_df

medical_df.info()

medical_df.describe()

medical_df["sex"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f",
                                      ylabel = "", title = "Sex of Recepients");

medical_df["smoker"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f",
                                         ylabel = "", title = "Number of smokers");

medical_df["region"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f",
                                         ylabel = "", title = "Regions")

medical_df["age"].plot(kind = "hist", edgecolor = "black");

medical_df["bmi"].plot(kind = "box", vert = False);

medical_df["charges"].plot(kind = "box", vert = False);

"""## 1. Analyze the Data with Plotly"""

import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# fig = px.histogram(medical_df, x = "age", marginal = "box", nbins = 47,
#                    title = "Distribution of Age")
# fig.update_layout(bargap = 0.1)
# fig.show()

# fig = px.histogram(medical_df, x = "bmi", marginal = "box", nbins = 47,
#                    color_discrete_sequence = ["red"], title = "Distribution of Age")
# fig.update_layout(bargap = 0.1)
# fig.show()

# fig = px.histogram(medical_df, x = "charges", marginal = "box", color = "smoker",
#                    color_discrete_sequence = ["green", "gray"], title = "Annual Medical Charges")
# fig.update_layout(bargap = 0.2)
# fig.show()

# fig = px.histogram(medical_df, x = "charges", marginal = "box", color = "sex",
#                    color_discrete_sequence = ["green", "gray"], title = "Annual Medical Charges")
# fig.update_layout(bargap = 0.2)
# fig.show()

# fig = px.histogram(medical_df, x = "charges", marginal = "box", color = "region",
#                    color_discrete_sequence = ["green", "gray", "yellow", "magenta"], title = "Annual Medical Charges")
# fig.update_layout(bargap = 0.2)
# fig.show()

# px.histogram(medical_df, x = "smoker", color = "sex", title = "Smokers")

# fig = px.scatter(medical_df, x = "age", y = "charges", color = "smoker",
#                  opacity = 0.8, hover_data= ["sex"], title = "Age vs Charges")
# fig.update_traces(marker_size = 5)
# fig.show()

# fig = px.scatter(medical_df, x = "bmi", y = "charges", color = "smoker",
#                  opacity = 0.8, hover_data= ["sex"], title = "BMI vs Charges")
# fig.update_traces(marker_size = 5)
# fig.show()

"""## 2. Detailed Analysis with Pandas Library"""

medical_df_age = medical_df.groupby(["age"])["charges"].agg(["min", "max", "median"])
#medical_df_age

medical_df_age.plot(kind = "line")

plt.title("The Relation Between Person's Age and its Medical Charge")
plt.xlabel("Age")
plt.ylabel("Medical Charges")
ax = plt.gca()
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, pos: f'${int(y/1000)}K'))
plt.show()

medical_df_men = medical_df[medical_df["sex"] == "male"]
medical_df_women = medical_df[medical_df["sex"] == "female"]

medical_df_age_men = medical_df_men.groupby(["age"])["charges"].agg(["min", "max", "median"])
medical_df_age_women = medical_df_women.groupby(["age"])["charges"].agg(["min", "max", "median"])

medical_df_age_men.index

fig, ax = plt.subplots(3, 1, figsize=(12, 10))

metrics = [
    ("median", "Median Medical Charge vs. Age for Men and Women"),
    ("min", "Min Medical Charge vs. Age for Men and Women"),
    ("max", "Max Medical Charge vs. Age for Men and Women")
]

formatter = plt.FuncFormatter(lambda y, pos: f'${int(y/1000)}K')

for i, (metric, title) in enumerate(metrics):
    medical_df_age_men[metric].plot(kind="line", ax=ax[i], label="Men")
    medical_df_age_women[metric].plot(kind="line", ax=ax[i], label="Women")

    ax[i].set_title(title)
    ax[i].set_xlabel("Age")
    ax[i].set_ylabel("Medical Charges")
    ax[i].yaxis.set_major_formatter(formatter)
    ax[i].legend()

plt.tight_layout()
plt.show()

medical_df["children"].value_counts()

medical_df_children = medical_df.groupby(["children"])["charges"].agg(["min", "max", "median"])
medical_df_children

medical_df_children.plot(kind = "line")

plt.title("The Relation Between Number of Children and Medical Charge")
plt.xlabel("Number of Children")
plt.ylabel("Medical Charges")
ax = plt.gca()
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, pos: f'${int(y/1000)}K'))
plt.show()

df_region_pivot = pd.pivot_table(data = medical_df, values = "charges", index = "region", columns = "sex", aggfunc = "median")

formatter = plt.FuncFormatter(lambda y, pos: f'${int(y/1000)}K')

df_region_pivot.plot(kind = "bar", rot = 45, figsize = (12, 10),
                      xlabel = "Region", ylabel = "Charges",
                      title = "Charges in Regions by Sex");
ax = plt.gca()
ax.yaxis.set_major_formatter(formatter)

medical_df.info()

"""## 3. Correlation Between Features"""

medical_df.charges.corr(medical_df.age)

medical_df.charges.corr(medical_df.bmi)

smoker_values = {"no": 0, "yes": 1}
smoker_numeric = medical_df.smoker.map(smoker_values)
smoker_numeric

medical_df.charges.corr(smoker_numeric)

medical_df_corr = medical_df.select_dtypes(include=['number']).corr()
medical_df_corr

sns.heatmap(medical_df_corr, cmap = "Reds", annot = True)
plt.title("Correlation Matrix");

"""## 4. Implement Custom Linear Regression Model and a Loss Function"""

non_smoker_df = medical_df[medical_df["smoker"] == "no"]
#non_smoker_df

sns.scatterplot(data = non_smoker_df, x = "age", y = "charges", alpha = 0.7,)

# Try this linear model: charges = w * age + b (y = w*x + b)
def linear_regression_charges (age, w , b):
    return w*age + b

import numpy as np

def loss_rmse(targets, predictions):
    return np.sqrt(np.mean(np.square(targets - predictions)))

def test_parameters(w, b):
    ages = non_smoker_df["age"]
    target = non_smoker_df["charges"]

    estimated_charges = linear_regression_charges(ages, w, b)

    plt.figure(figsize = (10, 6))

    plt.plot(ages, estimated_charges, "m", alpha = 0.9)
    plt.scatter(ages, target, s = 8, alpha = 0.8)

    plt.xlabel("Ages")
    plt.ylabel("Charges")
    plt.legend(["Estimated", "Actual"])
    plt.show()

    loss = loss_rmse(target, estimated_charges)
    print(loss)

test_parameters(290, -4300)

"""## 5. Simple Linear Regression Model using Scikit-learn Library"""

from sklearn.linear_model import LinearRegression

model = LinearRegression()

inputs = non_smoker_df[["age"]]
targets = non_smoker_df["charges"]

inputs.shape, targets.shape

model.fit(inputs, targets)

predictions = model.predict(inputs)
predictions

loss_rmse(targets, predictions)

model.coef_, model.intercept_

"""## 6. Turn Categorical Data into Numerical"""

smokers_df = medical_df[medical_df["smoker"] == "yes"]
smokers_df

sns.scatterplot(data = smokers_df, x = "age", y = "charges", alpha = 0.7,)

input_smokers = smokers_df[["age"]]
target_smokers = smokers_df["charges"]

model_smokers = LinearRegression()
model_smokers.fit(input_smokers, target_smokers)

predictions_smokers = model_smokers.predict(input_smokers)
loss_smokers = loss_rmse(target_smokers, predictions_smokers)
print(loss_smokers)

inputs, targets = non_smoker_df[["age", "bmi"]], non_smoker_df["charges"]

model = LinearRegression().fit(inputs, targets)
model_predictions = model.predict(inputs)

loss = loss_rmse(targets, model_predictions)
loss

non_smoker_df["charges"].corr(non_smoker_df.bmi)

plt.figure(figsize = (12, 10))

plt.scatter(x = non_smoker_df["bmi"], y = non_smoker_df["charges"],)

plt.xlabel("BMI")
plt.ylabel("Charges")
plt.title("BMI vs Charges")
plt.show()

model.coef_, model.intercept_

# Train bmi vs charges

sns.barplot(data = medical_df, x = "smoker", y = "charges");

smoker_numerical = {"no": 0, "yes": 1}
medical_df.insert(loc = 5, column = "smoker_numerical", value = medical_df["smoker"].map(smoker_numerical))
#medical_df["smoker_numerical"] = medical_df["smoker"].map(smoker_numerical)

sns.barplot(data = medical_df, x = "sex", y = "charges");

sex_numerical = {"female": 0 , "male": 1}
medical_df.insert(loc = 2, column = "sex_numerical", value = medical_df["sex"].map(sex_numerical))

sns.barplot(data = medical_df, x = "region", y = "charges", hue = "region", palette = "Paired", legend = False);

from sklearn import preprocessing

enc = preprocessing.OneHotEncoder()
enc.fit(medical_df[["region"]])
categories_region = enc.categories_[0]
categories_region

# Test Function
enc.transform(pd.DataFrame([["northeast"]], columns=["region"])).toarray()

one_hot = enc.transform(medical_df[["region"]]).toarray()

df_enc = pd.DataFrame(data = one_hot, columns = categories_region, index = medical_df.index)
medical_df = pd.concat([medical_df, df_enc], axis = 1)

medical_df

input_cols = ["age", "sex_numerical", "bmi", "children", "smoker_numerical",
              "northeast", "northwest", "southeast", "southwest"]
inputs, targets = medical_df[input_cols], medical_df["charges"]

model = LinearRegression().fit(inputs, targets)
predictions =  model.predict(inputs)

loss = loss_rmse(targets, predictions)
loss

medical_df[input_cols]

"""## 7. Divide the Data into Train and Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(inputs, targets, test_size=0.1)

# Create and train the model
model = LinearRegression().fit(X_train, y_train)

# Generate predictions
predictions_test = model.predict(X_test)

# Compute loss to evalute the model
loss = loss_rmse(y_test, predictions_test)
print('Test Loss:', loss)

# Generate predictions
predictions_train = model.predict(X_train)

# Compute loss to evalute the model
loss = loss_rmse(y_train, predictions_train)
print('Training Loss:', loss)

"""## 8. Linear Models for Smoking and Non-Smoking People

### 8.1 People that smoke (smoker)
"""

medical_df

df_smoker = medical_df[medical_df["smoker"] == "yes"]

df_smoker

inputs_cols = ["age", "sex_numerical", "bmi", "children", "northeast",
              "northwest", "southeast", "southwest"]
inputs = df_smoker[inputs_cols]
targets = df_smoker["charges"]
#inputs, targets

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(inputs)

scaled_input = scaler.transform(inputs)
scaled_input

model_smoker = LinearRegression().fit(scaled_input, targets)
predictions = model_smoker.predict(scaled_input)

loss = loss_rmse(targets, predictions)
loss

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(inputs, targets, test_size=0.1)     # Test with scaled_input

model_smoker_2 = LinearRegression().fit(X_train, y_train)
predictions_test = model_smoker_2.predict(X_test)
predictions_train = model_smoker_2.predict(X_train)

loss_train = loss_rmse(y_train, predictions_train)
loss_test = loss_rmse(y_test, predictions_test)

print(f"Train loss: {loss_train}, Test Loss: {loss_test}")

# 4191

"""### 8.2 People that do not smoke (non-smoker)"""

df_non_smoker = medical_df[medical_df["smoker"] == "no"]

df_non_smoker

inputs_cols = ["age", "sex_numerical", "bmi", "children", "northeast",
              "northwest", "southeast", "southwest"]
inputs = df_non_smoker[inputs_cols]
targets = df_non_smoker["charges"]
#inputs, targets

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(inputs)

scaled_input = scaler.transform(inputs)
scaled_input

model_non_smoker = LinearRegression().fit(scaled_input, targets)
predictions = model_non_smoker.predict(scaled_input)

loss = loss_rmse(targets, predictions)
loss

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(inputs, targets, test_size=0.1)     # Test with scaled_input

model_non_smoker_2 = LinearRegression().fit(X_train, y_train)
predictions_test = model_non_smoker_2.predict(X_test)
predictions_train = model_non_smoker_2.predict(X_train)

loss_train = loss_rmse(y_train, predictions_train)
loss_test = loss_rmse(y_test, predictions_test)

print(f"Train loss: {loss_train}, Test Loss: {loss_test}")