# -*- coding: utf-8 -*-
"""2_Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X13F70QrWHGi9XCRQRTMOe62FXbIb-zu

A Logistic Regression model is developed to classify the possibility of raining the next day. The ML model is trained over Rain in Australia Dataset.

## 0. Downloading the Dataset
"""

!pip install opendatasets --upgrade --quiet

import opendatasets as od

od.version()

dataset_url = "https://www.kaggle.com/jsphyg/weather-dataset-rattle-package"

od.download(dataset_url)

import os
import pandas as pd

data_dir = "/content/weather-dataset-rattle-package"
train_csv = data_dir + "/weatherAUS.csv"

raw_df = pd.read_csv(train_csv)

pd.set_option("display.max_columns", None)

raw_df.head()

raw_df.info()

raw_df.dropna(subset = ["RainToday", "RainTomorrow"], inplace = True)
raw_df.info()

"""## 1. Analyze Dataset"""

import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

"""### 1.1 Plotly Plots"""

#px.histogram(raw_df, x = "Location", title = "Location vs Rainy Days", color = "RainToday")

#px.histogram(raw_df, x = "Temp3pm", title = "Temperature at 3 pm vs Rain Today", color = "RainToday")

#px.histogram(raw_df, x = "RainToday", color = "RainToday", title = "Rain Tomorrow vs Rain Today")

# px.scatter(raw_df.sample(2000), title = "Min Temp. vs Max Temp.", x = "MinTemp",
#            y = "MaxTemp", color = "RainToday")

"""### 1.2 Matplotlib Plots"""

df_location = raw_df.pivot_table(index = "Location",
                                 columns = "RainToday",
                                 aggfunc = "size")

df_location.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'], figsize=(12, 6))

plt.xlabel("Location")
plt.ylabel("Count")
plt.title("Location vs. Rainy Days")
plt.legend(title = "RainToday", labels = ["No", "Yes"])
#plt.xticks(rotation = 90)
plt.tight_layout()
plt.show()

df_temp_3pm = raw_df.pivot_table(index = "Temp3pm",
                                 columns = "RainTomorrow",
                                 aggfunc = "size")

df_temp_3pm.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'],
                 xlabel = "Temperature", ylabel = "Count", figsize=(12, 6));

ax = plt.gca()
for i, label in enumerate(ax.xaxis.get_ticklabels()):
    if i % 20 != 0:
        label.set_visible(False)

df_rain_relation = raw_df.pivot_table(index = "RainToday",
                                      columns = "RainTomorrow",
                                      aggfunc = "size")
df_rain_relation.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'], rot = 0);

"""## 2. Train and Test Split

### 2.1 Sklearn `train_test_split`
"""

from sklearn.model_selection import train_test_split

temp_df, test_df = train_test_split(raw_df, test_size = 0.2, random_state = 42)
train_df, val_df = train_test_split(temp_df, test_size = 0.25, random_state = 42)

train_df.shape, val_df.shape, test_df.shape

year = pd.to_datetime(raw_df.Date).dt.year

plt.title("Number of Rows per Year")
sns.countplot(x = year, hue = year, legend = False, palette = "tab10");

"""### 2.2 Year of Publishing"""

year = pd.to_datetime(raw_df.Date).dt.year

train_df = raw_df[year < 2015]
val_df = raw_df[year == 2015]
test_df = raw_df[year > 2015]

train_df.shape, val_df.shape, test_df.shape

"""## 3. Pre-processing the Data

### 3.1 Input Data and Target (Labels)
"""

raw_df.head()

input_cols = list(train_df.columns[1:-1])
target_col = "RainTomorrow"

print(input_cols)
print(target_col)

train_inputs = train_df[input_cols].copy()
train_target =  train_df[target_col].copy()

val_inputs = val_df[input_cols].copy()
val_target = val_df[target_col].copy()

test_inputs = test_df[input_cols].copy()
test_target = test_df[target_col].copy()

import numpy as np

numeric_cols = train_inputs.select_dtypes(include = np.number).columns.tolist()
categorical_cols = train_inputs.select_dtypes("object").columns.tolist()

numeric_cols, categorical_cols

train_inputs[numeric_cols].describe()

train_inputs[categorical_cols].nunique()

"""### 3.2 Impute Values"""

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = "mean")      # Median if there are a lot of outliers

imputer.fit(raw_df[numeric_cols])

list(imputer.statistics_)

train_inputs[numeric_cols] = imputer.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = imputer.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = imputer.transform(test_inputs[numeric_cols])

train_inputs[numeric_cols].isna().sum()

"""### 3.3 Scaling"""

imputer.get_params()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(raw_df[numeric_cols])

print(f"The min values are: \n{scaler.data_min_}")
print(f"The max values are: \n{scaler.data_max_}")

train_inputs[numeric_cols] = scaler.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = scaler.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_inputs[numeric_cols])

train_inputs[numeric_cols].describe()

"""### 3.4 Encoding Categorical Data"""

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False, handle_unknown = "ignore")
encoder.fit(raw_df[categorical_cols])

encoder.categories_

encoded_cols = list(encoder.get_feature_names_out(categorical_cols))
print(encoded_cols)

# train_inputs[encoded_cols] = encoder.transform(train_inputs[categorical_cols])
# val_inputs[encoded_cols] = encoder.transform(val_inputs[categorical_cols])
# test_inputs[encoded_cols] = encoder.transform(test_inputs[categorical_cols])

train_inputs = pd.concat([train_inputs[numeric_cols], pd.DataFrame(encoder.transform(train_inputs[categorical_cols]), columns=encoded_cols, index=train_inputs.index)], axis=1)
val_inputs = pd.concat([val_inputs[numeric_cols], pd.DataFrame(encoder.transform(val_inputs[categorical_cols]), columns=encoded_cols, index=val_inputs.index)], axis=1)
test_inputs = pd.concat([test_inputs[numeric_cols], pd.DataFrame(encoder.transform(test_inputs[categorical_cols]), columns=encoded_cols, index=test_inputs.index)], axis=1)

"""## 4. Save Data Frames"""

train_inputs.shape, train_target.shape

val_inputs.shape, val_target.shape

test_inputs.shape, test_target.shape

import os
from pathlib import Path

save_files_dir = Path("save/")

if save_files_dir.is_dir():
    print(f"The {save_files_dir} directory exists.")
else:
    print(f"{save_files_dir} directory do not exists. Creating one...")
    save_files_dir.mkdir(parents = True, exist_ok = True)
    print(f"{save_files_dir} directory is created.")

train_inputs.to_parquet("save/train_inputs.parquet")
val_inputs.to_parquet("save/val_inputs.parquet")
test_inputs.to_parquet("save/test_inputs.parquet")

pd.DataFrame(train_target).to_parquet("save/train_target.parquet")
pd.DataFrame(val_target).to_parquet("save/val_target.parquet")
pd.DataFrame(test_target).to_parquet("save/test_target.parquet")

train_inputs = pd.read_parquet('save/train_inputs.parquet')
val_inputs = pd.read_parquet('save/val_inputs.parquet')
test_inputs = pd.read_parquet('save/test_inputs.parquet')

train_target = pd.read_parquet('save/train_target.parquet')[target_col]
val_target = pd.read_parquet('save/val_target.parquet')[target_col]
test_target = pd.read_parquet('save/test_target.parquet')[target_col]

"""## 5. Logistic Regression Model"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver = "liblinear")
model.fit(train_inputs[numeric_cols + encoded_cols], train_target)

pd.DataFrame({
    "features": numeric_cols + encoded_cols,
    "weights": model.coef_.tolist()[0]
})

"""## 6. Making Predictions and Evaluating the Model"""

X_train = train_inputs[numeric_cols + encoded_cols]
X_val = val_inputs[numeric_cols + encoded_cols]
X_test = test_inputs[numeric_cols + encoded_cols]

train_preds = model.predict(X_train)

train_preds

train_target

train_probs = model.predict_proba(X_train)
train_probs

model.classes_

from sklearn.metrics import accuracy_score

accuracy_score(train_target, train_preds)

from sklearn.metrics import confusion_matrix

confusion_matrix(train_target, train_preds, normalize = "true")

def pred_and_plot(inputs, target, name = ""):
    preds = model.predict(inputs)

    accuracy = accuracy_score(target, preds)
    print(f"Accuracy is: {accuracy * 100:.2f}%")
    conf_matrix = confusion_matrix(target, preds, normalize = "true")

    plt.figure()
    sns.heatmap(conf_matrix, annot = True)
    plt.xlabel("Predictions")
    plt.ylabel("Target")
    plt.title(f"{name} Confusion Matrix")

    return preds

train_preds = pred_and_plot(X_train, train_target, "Training")

val_preds = pred_and_plot(X_val, val_target, "Validation")

test_pred = pred_and_plot(X_test, test_target, "Test")

def random_guess(inputs):
    return np.random.choice(["No", "Yes"], len(inputs))

def all_no(inputs):
    return np.full(len(inputs), "No")

accuracy_score(test_target, random_guess(X_test))

accuracy_score(test_target, all_no(X_test))

"""## 7. Make Predictions on a Single Input"""

new_input = {"Date": "2022-03-04",
             "Location": "Katherine",
             "MinTemp": 20.9,
             "MaxTemp": 40.2,
             "Rainfall": 12.2,
             "Evaporation": 1.8,
             "Sunshine": np.nan,
             "WindGustDir": "NW",
             "WindGustSpeed": 49.9,
             "WindDir9am": "NW",
             "WindDir3pm": "NE",
             "WindSpeed9am": 10.4,
             "WindSpeed3pm": 18.9,
             "Humidity9am": 78.9,
             "Humidity3pm": 61.0,
             "Pressure9am": 1002.7,
             "Pressure3pm": 1001.1,
             "Cloud9am": 9.0,
             "Cloud3pm": 6.0,
             "Temp9am": 24.8,
             "Temp3pm": 34.1,
             "RainToday": "No"}

new_input_df = pd.DataFrame([new_input])
new_input_df

new_input_df[numeric_cols] = imputer.transform(new_input_df[numeric_cols])
new_input_df[numeric_cols] = scaler.transform(new_input_df[numeric_cols])
new_input_df[encoded_cols] = encoder.transform(new_input_df[categorical_cols])

X_new_input = new_input_df[numeric_cols + encoded_cols]
X_new_input

prediction = model.predict(X_new_input)[0]
prediction

prob = model.predict_proba(X_new_input)[0]
prob

def predict_input(single_input):
    input_df = pd.DataFrame([single_input])
    input_df[numeric_cols] = imputer.transform(input_df[numeric_cols])
    input_df[numeric_cols] = scaler.transform(input_df[numeric_cols])
    input_df[encoded_cols] = encoder.transform(input_df[categorical_cols])
    X_input = input_df[numeric_cols + encoded_cols]
    pred = model.predict(X_input)[0]
    prob = model.predict_proba(X_input)[0][list(model.classes_).index(pred)]
    return pred, prob