# -*- coding: utf-8 -*-
"""3_Desicion_Tree_and_Random_Forest_Opt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5jxw8RA_RSNd32y4SimP5ezwwaAv-Ek

Decision Tree and Random Forest Algorithms are trained over Australia weather dataset. It is also applied an approach that finds the best hyperparameters for the model.

## 0. Downloading the Dataset
"""

!pip install opendatasets --upgrade --quiet

import opendatasets as od
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

dataset_url = "https://www.kaggle.com/jsphyg/weather-dataset-rattle-package"

od.download(dataset_url)

raw_df = pd.read_csv("/content/weather-dataset-rattle-package/weatherAUS.csv")
raw_df

raw_df.info()

raw_df.dropna(subset = ["RainToday", "RainTomorrow"], inplace = True)
raw_df.info()

"""## 1. Analyze the Dataset"""

df_location = raw_df.pivot_table(index = "Location",
                                 columns = "RainToday",
                                 aggfunc = "size")

df_location.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'], figsize=(12, 6))

plt.xlabel("Location")
plt.ylabel("Count")
plt.title("Location vs. Rainy Days")
plt.legend(title = "RainToday", labels = ["No", "Yes"])
#plt.xticks(rotation = 90)
plt.tight_layout()
plt.show()

df_temp_3pm = raw_df.pivot_table(index = "Temp3pm",
                                 columns = "RainTomorrow",
                                 aggfunc = "size")

df_temp_3pm.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'],
                 xlabel = "Temperature", ylabel = "Count", figsize=(12, 6));

ax = plt.gca()
for i, label in enumerate(ax.xaxis.get_ticklabels()):
    if i % 20 != 0:
        label.set_visible(False)

df_rain_relation = raw_df.pivot_table(index = "RainToday",
                                      columns = "RainTomorrow",
                                      aggfunc = "size")
df_rain_relation.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'], rot = 0);

"""## 2. Train and Test Split"""

year = pd.to_datetime(raw_df.Date).dt.year

train_df = raw_df[year < 2015]
val_df = raw_df[year == 2015]
test_df = raw_df[year > 2015]

train_df.shape, val_df.shape, test_df.shape

"""## 3. Pre-processing the data

### 3.1 Input Data and Target
"""

input_cols = list(train_df.columns)[1:-1]
target_col = "RainTomorrow"

train_inputs = train_df[input_cols].copy()
train_target =  train_df[target_col].copy()

val_inputs = val_df[input_cols].copy()
val_target = val_df[target_col].copy()

test_inputs = test_df[input_cols].copy()
test_target = test_df[target_col].copy()

numeric_cols = train_inputs.select_dtypes(include = np.number).columns.tolist()
categorical_cols = train_inputs.select_dtypes("object").columns.tolist()

"""### 3.2 Impute Values"""

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = "mean").fit(raw_df[numeric_cols])

train_inputs[numeric_cols] = imputer.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = imputer.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = imputer.transform(test_inputs[numeric_cols])

train_inputs[numeric_cols].isna().sum()

"""### 3.3 Scaling"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().fit(raw_df[numeric_cols])

train_inputs[numeric_cols] = scaler.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = scaler.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_inputs[numeric_cols])

"""### 3.4 Encoding Categorical Data"""

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False, handle_unknown = "ignore")
encoder.fit(raw_df[categorical_cols])

encoded_cols = list(encoder.get_feature_names_out(categorical_cols))
print(encoded_cols)

train_inputs = pd.concat([train_inputs[numeric_cols], pd.DataFrame(encoder.transform(train_inputs[categorical_cols]), columns = encoded_cols, index = train_inputs.index)], axis = 1)
val_inputs = pd.concat([val_inputs[numeric_cols], pd.DataFrame(encoder.transform(val_inputs[categorical_cols]), columns = encoded_cols, index = val_inputs.index)], axis = 1)
test_inputs = pd.concat([test_inputs[numeric_cols], pd.DataFrame(encoder.transform(test_inputs[categorical_cols]), columns = encoded_cols, index = test_inputs.index)], axis = 1)

train_inputs

X_train = train_inputs[numeric_cols + encoded_cols]
X_val = val_inputs[numeric_cols + encoded_cols]
X_test = test_inputs[numeric_cols + encoded_cols]

"""## 4. Decision Tree Model

### 4.1 Train and Evaluate the Model
"""

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state = 42)
model.fit(X_train, train_target)

from sklearn.metrics import accuracy_score, confusion_matrix

train_preds = model.predict(X_train)

accuracy_score(train_preds, train_target)

model.score(X_val, val_target)

"""### 4.2 Visualise the Model"""

from sklearn.tree import plot_tree, export_text

plt.figure(figsize = (80, 20))
plot_tree(model, feature_names = X_train.columns, max_depth = 2, filled = True);

model.tree_.max_depth

tree_text = export_text(model, max_depth = 10, feature_names = list(X_train.columns))
print(tree_text[:5000])

model.feature_importances_

importance_df = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
}).sort_values("importance", ascending = False)

importance_df.head(10)

sns.barplot(data = importance_df.head(10), x = "importance", y = "feature",
            hue = "feature", legend = False, palette = "tab10")
plt.title("Feature Importance of the Decision Tree");

"""### 4.3 Improve the Model"""

model = DecisionTreeClassifier(max_depth = 3, random_state = 42)            # max_depth equals 6 or 7 gives the best result
model.fit(X_train, train_target)

model.score(X_train, train_target)

model.score(X_val, val_target)

plt.figure(figsize = (80, 20))
plot_tree(model, feature_names = X_train.columns, filled = True, rounded = True, class_names = model.classes_);

print(export_text(model, feature_names = list(X_train.columns)))

"""### 4.4 `max_leaf_nodes`"""

model = DecisionTreeClassifier(max_leaf_nodes = 128, random_state = 42)
model.fit(X_train, train_target)

model.score(X_train, train_target)

model.score(X_val, val_target)

model.tree_.max_depth

model.get_params()

"""### 4.5 Search for the Best Model

Validation Accuracy to beat: 0.8471531394464276
"""

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

class_weights = [
    {"No": 1, "Yes": 1.5},
    {"No": 1, "Yes": 1.65},
    {"No": 1, "Yes": 1.8},
    {"No": 1, "Yes": 1.8}]

parameters_grid = {
    #"max_depth": [5, 7, 10, 13, 16, 19, 22, 25, 28, 30],
    #"min_samples_split": (np.arange(2, 11, 1)).tolist(),
    "min_samples_split": [2],
    #"min_samples_leaf": [1, 2, 4, 6, 8, 10],
    "min_samples_leaf": [1],
    "max_leaf_nodes": [32, 64, 128, 256, 512, 1024],
    #"max_fetures": 1000,
    "class_weight": class_weights
}

model_basic = DecisionTreeClassifier(random_state = 42)
grid_search = GridSearchCV(estimator = model_basic,
                           param_grid = parameters_grid,
                           cv = 5,
                           n_jobs = -1,
                           verbose = 2,
                           scoring = "accuracy")

grid_search.fit(X_train, train_target)
model_best_grid_search = grid_search.best_estimator_

train_preds_best_grid = model_best_grid_search.predict(X_train)
accuracy_score(train_preds_best_grid, train_target)

model_best_grid_search.score(X_val, val_target)

model_best_grid_search.score(X_test, test_target)

best_param_d_tr = grid_search.best_params_  # The parameters of the most accurate decision tree model
print(f"The best parameters of the decision tree model: {best_param_d_tr}")

"""### 4.6 The Best Model that is Fine-Tuned"""

model_best = DecisionTreeClassifier(max_depth = 10,
                                    min_samples_split = 2,
                                    min_samples_leaf = 1,
                                    random_state = 42,
                                    max_leaf_nodes = 256)  #256, 278
                                    #class_weight = {"No": 1.0, "Yes": 1.3})

model_best.fit(X_train, train_target)
preds_train_best_model = model_best.predict(X_train)

accuracy_score(preds_train_best_model, train_target)

model_best.score(X_val, val_target)

model_best.score(X_test, test_target)

"""## 5. Train a Random Forest Model

### 5.1 Implement a Random Forest Model
"""

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_jobs = -1, random_state = 42)
model.fit(X_train, train_target)

model.score(X_train, train_target)

model.score(X_val, val_target)

train_probs = model.predict_proba(X_train)
train_probs

len(model.estimators_)

model.estimators_[0]
# view the whole data

plt.figure(figsize = (80, 20))
plot_tree(model.estimators_[0], max_depth = 2, feature_names = X_train.columns, filled = True, rounded = True, class_names = model.classes_);

plt.figure(figsize = (80, 20))
plot_tree(model.estimators_[31], max_depth = 2, feature_names = X_train.columns, filled = True, rounded = True, class_names = model.classes_);

importance_df = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
}).sort_values("importance", ascending = False)

importance_df.head(10)

sns.barplot(data = importance_df.head(10), x = "importance", y = "feature",
            hue = "feature", legend = False, palette = "tab10")
plt.title("Feature Importance of the Decision Tree");

"""### 5.2 Fine-tune the Model"""

base_model = RandomForestClassifier(n_jobs = -1, random_state = 42).fit(X_train, train_target)

base_train_acc = base_model.score(X_train, train_target)
base_val_acc = base_model.score(X_val, val_target)

base_train_acc, base_val_acc

model = RandomForestClassifier(n_jobs = -1, random_state = 42, n_estimators = 10)       # you could increase n_estimators 50-500
model.fit(X_train, train_target)

model.score(X_train, train_target), model.score(X_val, val_target)      # Max_depth 27 gave the best result...