# -*- coding: utf-8 -*-
"""4_XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHE4Arl3vFmQCM0APTt7ptbA4GKHsWyw

## 0. Downloading the Dataset
"""

!pip install opendatasets --upgrade --quiet

import os
import pandas as pd
import numpy as np
import opendatasets as od
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost
import graphviz
import lightgbm

!pip list | grep lightgbm

dataset_url = "https://www.kaggle.com/competitions/rossmann-store-sales/data"

od.download(dataset_url)

ross_df = pd.read_csv("/content/rossmann-store-sales/train.csv", low_memory = False)
store_df = pd.read_csv("/content/rossmann-store-sales/store.csv")
test_df = pd.read_csv("/content/rossmann-store-sales/test.csv")
submission_df = pd.read_csv("/content/rossmann-store-sales/sample_submission.csv")

ross_df

ross_df.info()

store_df

store_df.info()

merged_df = ross_df.merge(store_df, how = "left", on = "Store")
merged_test_df = test_df.merge(store_df, how = "left", on = "Store")

merged_df

merged_test_df

"""## 1. Cleaning the Data"""

merged_df.duplicated().sum()

merged_df[merged_df["Open"] == 0].Sales.value_counts()

merged_df = merged_df[merged_df["Open"] == 1].copy()            # We don't remove any rows from the test set

round(merged_df.describe().T, 3)

"""## 2. Feature Engineering"""

def split_date(df):
    df["Date"] = pd.to_datetime(df["Date"])
    df["Year"] = df.Date.dt.year
    df["Month"] = df.Date.dt.month
    df["Day"] = df.Date.dt.day
    df["WeekOfYear"] = df.Date.dt.isocalendar().week

split_date(merged_df)
split_date(merged_test_df)

def competition_months(df):
    df["CompetitionOpen"] = 12 * (df.Year - df.CompetitionOpenSinceYear) + (df.Month - df.CompetitionOpenSinceMonth)
    df["CompetitionOpen"] = df["CompetitionOpen"].map(lambda x: 0 if x < 0 else x).fillna(0)

competition_months(merged_df)
competition_months(merged_test_df)

merged_df[["Date", "CompetitionDistance", "CompetitionOpenSinceYear", "CompetitionOpenSinceMonth", "CompetitionOpen"]].sample(50)

def check_promo_month(row):
    month2str = {1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun",
                 7: "Jul", 8: "Aug", 9: "Sept", 10: "Oct", 11: "Nov", 12: "Dec"}
    try:
        months = (row["PromoInterval"] or "").split(",")
        if row["Promo2Open"] and month2str[row["Month"]] in months:
            return 1
        else:
            return 0
    except Exception:
        return 0

def promo_cols(df):
    # Months since Promo2 was open
    df["Promo2Open"] = 12 * (df.Year - df.Promo2SinceYear) +  (df.WeekOfYear - df.Promo2SinceWeek) * 7 / 30.5
    df["Promo2Open"] = df["Promo2Open"].map(lambda x: 0 if x < 0 else x).fillna(0) * df["Promo2"]
    # Whether a new round of promotions was started in the current month
    df["IsPromo2Month"] = df.apply(check_promo_month, axis=1) * df["Promo2"]

promo_cols(merged_df)
promo_cols(merged_test_df)

merged_df[["Date", "Promo2", "Promo2SinceYear", "Promo2SinceWeek", "PromoInterval", "Promo2Open", "IsPromo2Month"]].sample(20)

"""## 3. EDA of the Data"""

sns.histplot(data = merged_df, x = "Sales");

sns.histplot(data = merged_df, x = "Sales");

plt.figure(figsize = (18, 8))
temp_df = merged_df.sample(40000)

sns.scatterplot(x = temp_df["Sales"], y = temp_df["Customers"], hue = temp_df.Date.dt.year, alpha = 0.8)
plt.title("Sales vs Customers")
plt.show()

plt.figure(figsize = (18, 8))
temp_df = merged_df.sample(40000)

sns.scatterplot(x = temp_df["Store"], y = temp_df["Sales"], hue = temp_df.Date.dt.year, alpha = 0.8)
plt.title("Stores vs Sales")
plt.show()

sns.barplot(data = merged_df, x = "DayOfWeek", y = "Sales");

sns.barplot(data = merged_df, x = "Promo", y = "Sales");

merged_df.corr(numeric_only=True)["Sales"].sort_values(ascending = False)

sns.barplot(data = merged_df, x = "Year", y = "Sales");

sns.barplot(data = merged_df, x = "Month", y = "Sales");

sales_and_stores_df = merged_df.groupby("Store")[["Customers", "Sales"]].agg("mean")
sales_and_stores_df

sales_and_stores_df.plot(kind = "line")

merged_df.info()

merged_test_df.info()

"""## 4. Train and Test Split"""

merged_df.columns

input_cols = ["Store", "DayOfWeek", "Promo", "StateHoliday", "SchoolHoliday",
              "StoreType", "Assortment", "CompetitionDistance", "CompetitionOpen",
              "Day", "Month", "Year", "WeekOfYear",  "Promo2",
              "Promo2Open", "IsPromo2Month"]

target_col = "Sales"

inputs = merged_df[input_cols].copy()
targets = merged_df[target_col].copy()

test_inputs = merged_test_df[input_cols].copy()

numeric_cols = ["Store", "Promo", "SchoolHoliday",
                "CompetitionDistance", "CompetitionOpen", "Promo2", "Promo2Open", "IsPromo2Month",
                "Day", "Month", "Year", "WeekOfYear"]

categorical_cols = ["DayOfWeek", "StateHoliday", "StoreType", "Assortment"]

"""## 5. Pre-processing

### 5.1 Impute Values
"""

inputs[numeric_cols].isna().sum()

test_inputs.isna().sum()

max_distance = inputs.CompetitionDistance.max()
max_distance

inputs["CompetitionDistance"].fillna(max_distance*2, inplace = True)
test_inputs["CompetitionDistance"].fillna(max_distance*2, inplace = True)

inputs.isna().sum()

"""## 5.2 Scale"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().fit(inputs[numeric_cols])
inputs[numeric_cols] = scaler.transform(inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_input[numeric_cols])

"""### 5.3 Encode One-Hot Vector"""

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False, handle_unknown = "ignore").fit(inputs[categorical_cols])
encoded_cols = list(encoder.get_feature_names_out(categorical_cols))

inputs = pd.concat([inputs[numeric_cols], pd.DataFrame(encoder.transform(inputs[categorical_cols]), columns = encoded_cols, index = inputs.index)], axis = 1)
test_inputs = pd.concat([test_inputs[numeric_cols], pd.DataFrame(encoder.transform(test_inputs[categorical_cols]), columns = encoded_cols, index = test_inputs.index)], axis = 1)

inputs

X_train = inputs[numeric_cols + encoded_cols]
X_test = test_inputs[numeric_cols + encoded_cols]

"""## 6. Gradient Boosting Machines

### 6.1 Implement Base Model
"""

# Overview the Scikit-learn API:
#
# https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn:~:text=list(string)-,Scikit%2DLearn%20API,-%EF%83%81

from xgboost import XGBRegressor

model = XGBRegressor(random_state = 42, n_jobs = -1, n_estimators = 20, max_depth = 4)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# model.fit(X_train, targets)

preds = model.predict(X_train)
preds

from sklearn.metrics import mean_squared_error

def rmse(a, b):
    return np.sqrt(mean_squared_error(a, b))

rmse(preds, targets)

merged_df["Sales"].min(), merged_df["Sales"].max()

"""### 6.2 Visualise the Results"""

from xgboost import plot_tree
from matplotlib.pylab import rcParams

rcParams["figure.figsize"] = (30, 30)

plot_tree(model, rankdir = "LR", tree_idx = 0);

plot_tree(model, rankdir = "LR", tree_idx = 1);

plot_tree(model, rankdir = "LR", tree_idx = 19);

trees = model.get_booster().get_dump()

len(trees)

print(trees[0])

importance_df = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
})
importance_df.sort_values("importance", ascending = False, inplace = True)

importance_df.head(15)

plt.figure(figsize = (10, 6))

sns.barplot(data = importance_df.head(10), x = "importance", y = "feature")
plt.title("Feature Importance")
plt.show()

"""## 7. Find the Best Hyperparameters for XGBoost"""

from sklearn.model_selection import train_test_split

X_train_best, X_val, train_targets, val_targets = train_test_split(X_train, targets, test_size = 0.1)

def test_params(**params):
    model = XGBRegressor(n_jobs = -1, random_state = 42, **params)
    model.fit(X_train, train_targets)
    train_rmse = rmse(model.predict(X_train), train_targets)
    val_rmse = rmse(model.predict(X_val), val_targets)
    print('Train RMSE: {}, Validation RMSE: {}'.format(train_rmse, val_rmse))

# Optimization Strategy
#1.n_estimators     2. max_depth    3. learning_rate    4. booster  5. Miscellaneous