# -*- coding: utf-8 -*-
"""Testing_ML_Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15C-O1dqmVHkvQWtTyRmIALiXGfx7G4cx

## 0. Downloading and Process the Data
"""

!pip install --quiet opendatasets

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import opendatasets as od
import seaborn as sns
import plotly.express as px

od.download("https://www.kaggle.com/competitions/rossmann-store-sales/data")

os.listdir("rossmann-store-sales")

ross_df = pd.read_csv("/content/rossmann-store-sales/train.csv", low_memory = False)

ross_df

store_df = pd.read_csv("/content/rossmann-store-sales/store.csv")

store_df

merged_df = ross_df.merge(store_df, how = "left", on = "Store")
merged_df

merged_df.shape

test_df = pd.read_csv("/content/rossmann-store-sales/test.csv")

test_df

merged_test_df = test_df.merge(store_df, how = "left", on = "Store")

merged_test_df

"""## 1. Cleaning the Data"""

merged_df.info()

round(merged_df.describe().T, 3)

merged_df.duplicated().sum()

merged_df["Date"] = pd.to_datetime(merged_df.Date)
merged_test_df["Date"] = pd.to_datetime(merged_test_df.Date)

merged_df["Date"].min(), merged_df["Date"].max()

merged_test_df["Date"].min(), merged_test_df["Date"].max()

"""## 2. EDA of the Data"""

sns.histplot(data = merged_df, x = "Sales");

merged_df["Open"].value_counts()

merged_df = merged_df[merged_df["Open"] == 1].copy()

sns.histplot(data = merged_df, x = "Sales");

plt.figure(figsize = (18, 8))
temp_df = merged_df.sample(40000)

sns.scatterplot(x = temp_df["Sales"], y = temp_df["Customers"], hue = temp_df.Date.dt.year, alpha = 0.8)
plt.title("Sales vs Customers")
plt.show()

plt.figure(figsize = (18, 8))
temp_df = merged_df.sample(40000)

sns.scatterplot(x = temp_df["Store"], y = temp_df["Sales"], hue = temp_df.Date.dt.year, alpha = 0.8)
plt.title("Stores vs Sales")
plt.show()

sns.barplot(data = merged_df, x = "DayOfWeek", y = "Sales");

sns.barplot(data = merged_df, x = "Promo", y = "Sales");

merged_df.corr(numeric_only=True)["Sales"].sort_values(ascending = False)

merged_df["Day"] = merged_df.Date.dt.day
merged_df["Month"] = merged_df.Date.dt.month
merged_df["Year"] = merged_df.Date.dt.year

merged_test_df["Day"] = merged_test_df.Date.dt.day
merged_test_df["Month"] = merged_test_df.Date.dt.month
merged_test_df["Year"] = merged_test_df.Date.dt.year

sns.barplot(data = merged_df, x = "Year", y = "Sales");

sns.barplot(data = merged_df, x = "Month", y = "Sales");

sales_and_stores_df = merged_df.groupby("Store")[["Customers", "Sales"]].agg("mean")
sales_and_stores_df

sales_and_stores_df.plot(kind = "line")

merged_df.info()

"""## 3. Train, Validation and Test Split"""

train_size = int(0.75 * len(merged_df))

sorted_df = merged_df.sort_values("Date")
train_df, val_df = sorted_df[:train_size], sorted_df[train_size:]
len(train_df), len(val_df)

train_df

train_df.columns

# input_cols = ["Store", "DayOfWeek", "Date", "Sales", "Customers", "Open", "Promo",
#               "StateHoliday", "SchoolHoliday", "StoreType", "Assortment",
#               "CompetitionDistance", "CompetitionOpenSinceMonth",
#               "CompetitionOpenSinceYear", "Promo2", "Promo2SinceWeek",
#               "Promo2SinceYear", "PromoInterval", "Day", "Month", "Year"]

input_cols = ["Store", "DayOfWeek", "Promo", "StateHoliday", "StoreType", "Assortment", "Day", "Month", "Year"]
target_col = "Sales"

merged_df[input_cols].nunique()         # Feature Engineering should be applied to the Num of Stores; Else a curse of dimensionality problem will occurs

train_inputs = train_df[input_cols].copy()
train_targets = train_df[target_col].copy()

val_inputs = val_df[input_cols].copy()
val_targets = val_df[target_col].copy()

test_inputs = merged_test_df[input_cols].copy()

numeric_cols = ["Store", "Day", "Month", "Year"]
categorical_cols = ["DayOfWeek", "Promo", "StateHoliday", "StoreType", "Assortment"]

"""## 4. Pre-processing

### 4.1 Impute Values
"""

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = "mean").fit(train_inputs[numeric_cols])

train_inputs[numeric_cols] = imputer.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = imputer.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = imputer.transform(test_inputs[numeric_cols])

"""### 4.2 Scale"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().fit(train_inputs[numeric_cols])

train_inputs[numeric_cols] = scaler.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = scaler.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_inputs[numeric_cols])

"""### 4.3 Encode One-Hot Vector"""

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False, handle_unknown = "ignore").fit(train_inputs[categorical_cols])
encoded_cols = list(encoder.get_feature_names_out(categorical_cols))

encoded_cols

train_inputs = pd.concat([train_inputs[numeric_cols], pd.DataFrame(encoder.transform(train_inputs[categorical_cols]), columns = encoded_cols, index = train_inputs.index)], axis = 1)
val_inputs = pd.concat([val_inputs[numeric_cols], pd.DataFrame(encoder.transform(val_inputs[categorical_cols]), columns = encoded_cols, index = val_inputs.index)], axis = 1)
test_inputs = pd.concat([test_inputs[numeric_cols], pd.DataFrame(encoder.transform(test_inputs[categorical_cols]), columns = encoded_cols, index = test_inputs.index)], axis = 1)

train_inputs

X_train = train_inputs[numeric_cols + encoded_cols]
X_val = val_inputs[numeric_cols + encoded_cols]
X_test = test_inputs[numeric_cols + encoded_cols]

"""## 5. Base Model"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

linear_regression_model = LinearRegression().fit(X_train, train_targets)

train_preds = linear_regression_model.predict(X_train)
val_preds= linear_regression_model.predict(X_val)

train_preds

np.sqrt(mean_squared_error(train_preds, train_targets))     # You need sqrt function for RMSE

np.sqrt(mean_squared_error(val_preds, val_targets))

"""## 6. More Complex Models

### 6.1 `try_model` Function
"""

def try_model(model):
    model.fit(X_train, train_targets)

    train_preds = model.predict(X_train)
    val_preds = model.predict(X_val)

    train_rmse = np.sqrt(mean_squared_error(train_targets, train_preds))
    val_rmse = np.sqrt(mean_squared_error(val_targets, val_preds))

    return train_rmse, val_rmse

try_model(linear_regression_model)

"""### 6.2 Linear Models"""

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, SGDRegressor

try_model(LinearRegression())

try_model(Ridge())

try_model(Lasso())

try_model(ElasticNet())

try_model(SGDRegressor())

"""## 6.3 Tree Based Models"""

from sklearn.tree import DecisionTreeRegressor, plot_tree

decision_tree_model = DecisionTreeRegressor(random_state = 42)
try_model(decision_tree_model)          # The model overfits

from sklearn.ensemble import RandomForestRegressor

random_forest_model = RandomForestRegressor(n_estimators = 50, random_state = 42, n_jobs = -1)
try_model(random_forest_model)
# (np.float64(474.9198974666898), np.float64(1371.7321923469985))       n_estimators = 100

random_forest_model.get_params()

"""## 7. Interpret the Results"""

X_train.columns

random_forest_model.feature_importances_

importance_df = pd.DataFrame({
    "feature": X_train.columns,
    "importance": random_forest_model.feature_importances_
})

importance_df.sort_values("importance", ascending = False, inplace = True)
#importance_df.head(15)

sns.barplot(data = importance_df.head(10), x = "importance", y = "feature");

"""## 8. Submission on Kaggle"""

test_preds = decision_tree_model.predict(X_test)
test_preds

submission_df = pd.read_csv("/content/rossmann-store-sales/sample_submission.csv")

submission_df["Sales"] = test_df["Open"].fillna(1).astype("int") * test_preds
submission_df

submission_df.to_csv("submission.csv", index = None)

!head submission.csv

