# -*- coding: utf-8 -*-
"""5_K-Means_DBSCAN_PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSqOJKEcszsiDuaD6xaB0_VhWwyZ8r2e

## 0. Downloading the Data
"""

!pip install opendatasets --upgrade --quiet

import os
import pandas as pd
import numpy as np
import opendatasets as od
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost
import graphviz
import lightgbm

iris_df = sns.load_dataset("iris")

iris_df

sns.scatterplot(data = iris_df, x = "sepal_length", y = "petal_length", hue = "species");

sns.scatterplot(data = iris_df, x = "sepal_length", y = "petal_length");    # Now it is hard to find the three clusters

numeric_cols = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

X = iris_df[numeric_cols]
X

"""## 1. K-Means"""

from sklearn.cluster import KMeans

model = KMeans(n_clusters = 3, random_state = 42)
model.fit(X)

model.cluster_centers_

X

preds = model.predict(X)
preds

model.cluster_centers_[:, 0]

sns.scatterplot(data = X, x = "sepal_length", y = "petal_length", hue = preds);
centers_x, centers_y = model.cluster_centers_[:, 0], model.cluster_centers_[:, 2]
plt.plot(centers_x, centers_y, "xb")
plt.show()

model.inertia_

model = KMeans(n_clusters = 6, random_state = 42).fit(X)

preds = model.predict(X)
preds

sns.scatterplot(data = X, x = "sepal_length", y = "petal_length", hue = preds);
centers_x, centers_y = model.cluster_centers_[:, 0], model.cluster_centers_[:, 2]
plt.plot(centers_x, centers_y, "xb")
plt.show()

model.inertia_

#
#
options = range(2, 11)
inertias = []

for n_clusters in options:
    model = KMeans(n_clusters, random_state=42).fit(X)
    inertias.append(model.inertia_)

plt.title("No. of clusters vs. Inertia")
plt.plot(options, inertias, "-o")
plt.xlabel("No. of clusters (K)")
plt.ylabel("Inertia");

"""## 2. DBSCAN"""

from sklearn.cluster import DBSCAN

model = DBSCAN(eps = 1.1, min_samples = 4)

model.fit(X)

model.labels_

model.core_sample_indices_

sns.scatterplot(data = X, x = "sepal_length", y = "petal_length", hue = model.labels_);

# eps / min_samples

"""## 3. Hierarchical Clustering

## 4. Dimensionality Reduction and Manifold Learning
"""

from sklearn.decomposition import PCA

pca = PCA(n_components = 2)

pca.fit(iris_df[numeric_cols])

transformed = pca.transform(iris_df[numeric_cols])

sns.scatterplot(x = transformed[:, 0], y = transformed[:, 1], hue = iris_df["species"]);        # hue = "model.labels_"

"""## 5. t-Distributed Stochastic Neighbour Embeddings (t-SNE)"""

from sklearn.manifold import TSNE

tsne = TSNE(n_components = 2)

transformed = tsne.fit_transform(iris_df[numeric_cols])

sns.scatterplot(x = transformed[:, 0], y = transformed[:, 1], hue = iris_df["species"]);
